

# install apache
- name: install apache
  apt: name={{ item }}
  with_items:
    - apache2

- name: update apache2 config
  copy: src=apache2.conf dest=/etc/apache2/sites-available/000-default.conf
  notify: restart apache2

- name: update apache2 envvars
  copy: src=apache2_envvars dest=/etc/apache2/envvars
  notify: restart apache2




# copy license and ztp script
- name: copy license
  copy: src=license.lic dest=/var/www/license.lic

- name: put rename script in /var/www
  copy: src=rename_eth_swp dest=/var/www/rename_eth_swp

- name: create the ztp script
  template: src=ztp.sh.j2 dest=/var/www/ztp.sh
